class AgentError(Exception):
    code: str | None
    def __init__(self, message: str, code: str | None = None) -> None: ...

class BudgetExceededError(AgentError): ...
class ApprovalDeniedError(AgentError): ...
class ModelError(AgentError): ...
class ToolError(AgentError): ...
class SkillError(AgentError): ...

def from_code(message: str, code: str | None) -> AgentError: ...
