[workspace]
resolver = "2"
members = [
    "crates/orchest-protocol",
    "crates/orchest-provider-core",
    "crates/orchest-provider-http",
    "crates/orchest-provider-stream",
    "crates/orchest-provider-visual",
    "crates/orchest-provider",
    "crates/orchest",
    "crates/orchest-py",
    "crates/orchest-node",
]

[workspace.lints.clippy]
too_many_lines = "warn"
too_many_arguments = "warn"
result_large_err = "warn"
